# Generated by Django 3.2 on 2021-04-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('title', models.CharField(max_length=25)),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
